import logo from '../../assets/logo.png'
import newLogo from '../../assets/new-logo.svg'
import ship from '../../assets/ship.png'
import box from '../../assets/box.png'
import date from '../../assets/date.png'
import location from '../../assets/location.png'
import ship2 from '../../assets/ship2.png'
import support from '../../assets/support.png'
import support1 from '../../assets/support1.png'
import support2 from '../../assets/support2.png'
import support3 from '../../assets/support3.png'
import comma from '../../assets/comma.png'
import arrow from '../../assets/arrow.png'
import facebook from '../../assets/facebook.svg'
import linkdin from '../../assets/linkdin.svg'
import twitter from '../../assets/twitter.svg'
import camera from '../../assets/camera.png'
import shipp from '../../assets/shipp.png'
import success from '../../assets/success.png'
import profile from '../../assets/profile.png'
import edit from '../../assets/edit.png'
import reset from '../../assets/reset.png'
import creditCard from '../../assets/creditCard.png'
import deleteAccount from '../../assets/delete.png'
import man from '../../assets/man.png'
import profile1 from '../../assets/profile1.png'
import banner from '../../assets/banner.png'
import delivery from '../../assets/delivery.png'
import check from '../../assets/check.png'
import tick from '../../assets/tick-mark.png'
import message1 from '../../assets/message1.png'
import message2 from '../../assets/message2.png'
import search from '../../assets/search.png'
import visa from '../../assets/visa.png'
import creditcardd from '../../assets/creditcardd.png'
import bin from '../../assets/bin.png'
import arrow2 from '../../assets/arrow2.png'
import map from '../../assets/map.png'
import bell from '../../assets/bell.png'
import men from '../../assets/men.png'
import user from '../../assets/user.png'
import owner from '../../assets/owner.svg'
import locationn from '../../assets/location.png'
import verified from '../../assets/verified.png'
import bussinessProfile from '../../assets/bussinessProfile.png'
import checkk from '../../assets/checkk.png'
import pdf from '../../assets/pdf.png'
import red from '../../assets/red.png'
import green from '../../assets/green.png'
import close from '../../assets/close.png'
import file from '../../assets/file.png'
import yes from '../../assets/yes.png'
import submit from '../../assets/submit.png'
import time from '../../assets/time.png'
import no from '../../assets/no-rq.png'
import card from '../../assets/creditcardd.png'
import logout from '../../assets/logout.png'
import container from '../../assets/container.png'
import report from '../../assets/report.png'
import newTop from '../../assets/new-top.png'
import book1 from '../../assets/book-1.png'
import book2 from '../../assets/book-2.png'
import book3 from '../../assets/book-3.png'
import client1 from '../../assets/client-1.png'
import client2 from '../../assets/client-2.png'
import logo0 from '../../assets/Logo-0.png'
import logo1 from '../../assets/Logo-1.png'
import logo2 from '../../assets/Logo-2.png'
import logo3 from '../../assets/Logo-3.png'
import logo4 from '../../assets/Logo-4.png'
import logo5 from '../../assets/Logo-5.png'
import largeCargoShip from '../../assets/large-cargo-ship-with-containers-port-generative-ai 1.png'
import logoFooter from '../../assets/logo-footer.png'
import loc from '../../assets/loc.png'
import calender from '../../assets/calendar.png'
import iccon from '../../assets/iccon.png'
import arow from '../../assets/arrow-right.png'
import arrowss from '../../assets/arrowss.png'
import Group from '../../assets/Group.png'
import twitters from '../../assets/twitter.png'
import instagram12 from '../../assets/instagram12.png'

export {
    logo,
    newLogo,
    ship,box,date,location,ship2,support,
    support1,support2,support3,comma,arrow,
    facebook,linkdin,twitter,camera,shipp,success,
    profile,edit,reset,creditCard,deleteAccount,man,profile1,
    banner,delivery,check,tick,message1,message2,search,visa,creditcardd,bin,arrow2,map,bell,men,
    user,owner,locationn,verified,bussinessProfile,checkk,pdf,red,green,close,file,yes,submit,time,no,card,logout,report,container,newTop,
    book1, book2, book3, client1, client2, logo0, logo1, logo2, logo3, logo4, logo5, largeCargoShip, logoFooter,loc,calender,iccon,arow,arrowss,Group,twitters,instagram12
}